test: add CPACK_SOURCE_PACKAGE_FILE_NAME for source generation and change order of job steps

diff --git a/.github/workflows/lzcomplexity_build.yml b/.github/workflows/lzcomplexity_build.yml
--- a/.github/workflows/lzcomplexity_build.yml
+++ b/.github/workflows/lzcomplexity_build.yml
@@ -119,22 +119,6 @@ jobs:
       - name: Install tools fof upload to PPA
         run: sudo apt-get install -y ssh gnupg dput devscripts debhelper
 
-      # Decode SSH private key
-      - name: Decode SSH private key
-        run: |
-          mkdir -p ~/.ssh
-          echo "$LAUNCHPAD_SSH_PRIVATE_KEY and secret: ${{ secrets.LAUNCHPAD_SSH_PRIVATE_KEY }}"
-          echo "${{ secrets.LAUNCHPAD_SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
-          chmod 600 ~/.ssh/id_ed25519
-
-      # Configure SSH
-      - name: Configure SSH
-        run: |
-          ssh-keyscan launchpad.net >> ~/.ssh/known_hosts
-          # ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_ed25519 launchpad.net || true
-          # Test SSH connection
-          ssh -T git@git.launchpad.net || true  # This will fail but shows key works
-
       # Set up GPG key for signing
       - name: Set up GPG key
         run: |
@@ -142,6 +126,17 @@ jobs:
           echo "${{ secrets.GPG_KEY_PASSPHRASE }}" | gpg --passphrase-fd 0 --export-secret-key -a > /dev/null 2>&1 || true
           # Verify the key is imported
           gpg --list-secret-keys
+
+      # Configure SSH
+      - name: Setup SSH for Launchpad
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.LAUNCHPAD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
+          # echo "${{ secrets.LAUNCHPAD_SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+          ssh-keyscan -H ppa.launchpad.net >> ~/.ssh/known_hosts
+          # Test SSH connection
+          ssh -T git@git.launchpad.net || true  # This will fail but shows key works
 
       # Configure dput config file
       - name: Configure dput for PPA upload
@@ -154,6 +149,13 @@ jobs:
           incoming = ~${{ secrets.LAUNCHPAD_USERNAME }}/ubuntu/${{ secrets.LAUNCHPAD_PPA }}/
           EOF
 
+      - name: Configure git for Launchpad
+        run: |
+          git config --global user.name "Efren Aragon"
+          git config --global user.email "${{ secrets.LAUNCHPAD_EMAIL }}"
+          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"
+          git config --global commit.gpgsign true
+
       - name: Prepare Debian source package
         env:
           LAUNCHPAD_EMAIL: ${{ secrets.LAUNCHPAD_EMAIL }}
@@ -165,6 +167,7 @@ jobs:
           
           # Extract tarball
           TARBALL_NAME=$(basename ${{ github.workspace }}/_packages/*.tar.gz)
+          echo "tar file: ${TARBALL_NAME}"
           tar -xzf ${TARBALL_NAME} -C ~/packaging/
           
           # If your project already has a debian directory, copy it
